/**
 * 
 */
package uk.ac.manchester.cs.pronto;

import java.util.Collection;
import java.util.Map;
import java.util.Set;

import org.mindswap.pellet.KnowledgeBase;
import org.semanticweb.owlapi.model.OWLClassExpression;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * <p>Title: PTBox</p>
 * 
 * <p>Description: 
 *  Probabilistic TBox (PTBox) = classical KB + set of default conditional constraints
 * </p>
 * 
 * <p>Copyright: Copyright (c) 2007, 2008</p>
 * 
 * <p>Company: Clark & Parsia, LLC. <http://www.clarkparsia.com></p>
 * 
 * @author pavel
 */
public interface PTBox {

	public KnowledgeBase getClassicalKnowledgeBase();

	public Set<ConditionalConstraint> getDefaultConstraints();
	public void setDefaultConstraints(Set<ConditionalConstraint> ccSet);
	public boolean addDefaultConstraint(ConditionalConstraint cc);
	public Set<ConditionalConstraint> addDefaultConstraints(Set<ConditionalConstraint> ccSet);
	public void removeDefaultConstraint(ConditionalConstraint cc);
	public void removeDefaultConstraints(Collection<ConditionalConstraint> ccSet);
	public String getID();
	
	public PTBox clone();
	public PTBox clone(boolean copyConstraints);
	
	public void reset();
	public boolean getChanged();
	
	/**
	 * All implementations must return actual reference to the supplemental data, not a copy of it
	 * 
	 * @return
	 */
	public PTBoxSuppData getSupplementalData();
	public void preprocess();
	
	public OWLOntology getClassicalOntology();
	public void setClassicalOntology(OWLOntology ontology);
	public Map<String, OWLClassExpression> getAutoGeneratedClasses();
	public void setAutoGeneratedClasses(Map<String, OWLClassExpression> nameMap);
	//Transforms any auto generated class names back to the original expressions
	public ConditionalConstraint translateConstraint(ConditionalConstraint cc);
}
