package uk.ac.manchester.cs.pronto.io;

import java.util.Map;

import org.junit.Test;
import org.semanticweb.owlapi.model.OWLClassExpression;

import aterm.ATermAppl;

import uk.ac.manchester.cs.pronto.ConditionalConstraint;
import uk.ac.manchester.cs.pronto.ProbKnowledgeBase;
import uk.ac.manchester.cs.pronto.ProntoMainTestSuite;


public class KBLoaderTest {

	private static final String	FILE_PREFIX	= "file:" + ProntoMainTestSuite.BASE + "io/";
	
	@Test
	public void testLoad1() throws Exception {
		
		/**
		 * Not quite a JUnit test yet.. 
		 */
		
		ProbKnowledgeBase pkb = new KBStandaloneLoader().load( FILE_PREFIX + "test_owlxml.owl" );

		for (ConditionalConstraint cc : pkb.getPTBox().getDefaultConstraints()) {
			
			System.out.println("(" + cc.getConclusion() + "|" + cc.getEvidence() + ")");	
		}
		
		System.out.println("Axioms:");
		
		for (ATermAppl axiom : pkb.getPTBox().getClassicalKnowledgeBase().getTBox().getAxioms()) {
			
			System.out.println(axiom);
		}
		
		System.out.println("Name map:");
		
		for (Map.Entry<String, OWLClassExpression> entry : pkb.getPTBox().getAutoGeneratedClasses().entrySet()) {
			
			System.out.println(entry);
		}		
	}	
}
